spring:
  datasource:
    name: ctsystem
    url: jdbc:mysql://localhost:3306/ctsystem?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.youy.entity
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@uk1:7001/eureka/,http://admin:admin@uk2:7002/eureka/
  instance:
    prefer-ip-address: true
